version: '3'

services:
  hiroshi:
   restart: unless-stopped
   image: pysergio/hiroshi:latest
   environment:
     TELEGRAM_BOT_TOKEN: 1111111111:SOME_REAL_TOKEN_HERE
     USERS_WHITELIST: "@YouUserName,@YourFriendUserName"
     REDIS: "redis://redis"

  redis:
    restart: unless-stopped
    image: redis:6-alpine
    volumes:
      - redis-data:/data

volumes:
  redis-data:
